"""
6_DTC_Analysis.py — Deferred Tax Credit overhang analysis for the four Greek systemic banks.
"""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parents[1]))

import streamlit as st
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import pandas as pd
import numpy as np

from utils.data import (
    load_kpis, BANKS, YEARS, COLORS, LAYOUT,
    DTC_DATA, GOODWILL_DATA, INTANGIBLES_DATA,
)

st.set_page_config(page_title="DTC Analysis", page_icon="🏦", layout="wide")

with st.sidebar:
    st.markdown("### 🏦 DTC Analysis")
    st.caption(
        "Deferred Tax Credits (DTCs) are the single largest capital quality issue "
        "for Greek systemic banks. They originate from PSI-era loan losses "
        "crystallised under Greek Law 4172/2013."
    )
    st.divider()
    st.caption(
        "**Data notes:**  \n"
        "Eurobank 2023/2024 DTC confirmed from annual report.  \n"
        "All other figures: estimated from Bloomberg sector total (~€12.5bn mid-2024) "
        "and proportional DTA allocation (investing.com balance sheets).  \n"
        "Accuracy ±€200–300m — use for directional analysis."
    )


@st.cache_data
def get_kpis():
    return load_kpis()


kpis = get_kpis()

# ── Build DTC DataFrame ───────────────────────────────────────────────────────
dtc_rows = []
for bank in BANKS:
    for year in YEARS:
        krow   = kpis[(kpis.bank == bank) & (kpis.year == year)]
        equity = krow["equity"].values[0]  if len(krow) else None
        cet1   = krow["cet1"].values[0]    if len(krow) else None
        dtc    = DTC_DATA.get(bank, {}).get(year)
        dtc_rows.append({
            "bank":           bank,
            "year":           year,
            "dtc_eur_m":      dtc,
            "equity":         equity,
            "dtc_pct_equity": round(dtc / equity * 100, 1) if (dtc and equity) else None,
            "yoy_change":     None,  # filled below
        })

dtc_df = pd.DataFrame(dtc_rows)

# Year-over-year DTC reduction per bank
for bank in BANKS:
    mask = dtc_df.bank == bank
    dtc_df.loc[mask, "yoy_change"] = dtc_df.loc[mask, "dtc_eur_m"].diff().values

# ── Header ────────────────────────────────────────────────────────────────────
st.title("Deferred Tax Credit (DTC) Analysis")
st.caption("PSI-era capital quality overhang — four Greek systemic banks, FY2022–2024")
st.divider()

# ── Context ───────────────────────────────────────────────────────────────────
st.subheader("What Are DTCs and Why Do They Matter?")
st.markdown("""
Greek banks hold a large stock of **Deferred Tax Assets (DTAs)** originating from loan-loss provisions
made during the 2010–2015 sovereign and economic crisis, including losses from the **2012 PSI (Private Sector Involvement)**
— the largest sovereign debt restructuring in history.

Greek **Law 4172/2013** converted most of these DTAs into **Deferred Tax Credits (DTCs)**: state-guaranteed
instruments where the Greek government guarantees the bank will receive a cash payment if the DTA
cannot be offset against future taxable profits. This guarantee makes DTCs eligible for inclusion in **CET1 capital**
under CRR Article 39.

**Why this matters for capital quality:**
- DTCs are not generated by the bank's own earnings — they are a state subsidy disguised as capital
- ECB supervisors, credit rating agencies, and institutional investors apply a quality discount to CET1 ratios with high DTC content
- The higher the DTC-to-CET1 ratio, the more a bank's capital adequacy depends on the Greek sovereign's fiscal health
- All four banks have committed to accelerating DTC derecognition from 2041 to **2032–2034** by voluntarily
  deducting DTCs from regulatory capital ahead of the statutory tax-offset schedule
""")
st.divider()

# ── DTC Stock Chart ───────────────────────────────────────────────────────────
st.subheader("DTC Stock (€m) — 2022–2024")

fig_stock = go.Figure()
for bank in BANKS:
    bdata = dtc_df[dtc_df.bank == bank].sort_values("year")
    fig_stock.add_trace(go.Bar(
        x=bdata["year"],
        y=bdata["dtc_eur_m"],
        name=bank,
        marker_color=COLORS[bank],
        text=[f"€{v/1000:.2f}bn" for v in bdata["dtc_eur_m"]],
        textposition="outside",
        hovertemplate=f"<b>{bank}</b><br>Year: %{{x}}<br>DTC: €%{{y:,.0f}}m<extra></extra>",
    ))

# Sector total annotation line
for year in YEARS:
    sector_total = sum(DTC_DATA[b][year] for b in BANKS)
    fig_stock.add_annotation(
        x=year, y=sector_total + 300,
        text=f"Sector: €{sector_total/1000:.1f}bn",
        showarrow=False,
        font=dict(color="#94a3b8", size=10),
    )

fig_stock.update_layout(
    **LAYOUT,
    barmode="group",
    title="DTC Stock per Bank (€m)",
    height=420,
    legend=dict(bgcolor="rgba(0,0,0,0)", font=dict(color="#94a3b8")),
)
fig_stock.update_yaxes(tickprefix="€", ticksuffix="m")
st.plotly_chart(fig_stock, use_container_width=True)
st.caption(
    "Eurobank 2023/2024 confirmed from annual report. Other figures estimated from "
    "Bloomberg sector total (€12.5bn mid-2024) and DTA proportional allocation. "
    "Sector total declining ~€750–800m/year through linear amortisation."
)

st.divider()

# ── DTC as % of Equity ────────────────────────────────────────────────────────
st.subheader("DTC as % of Total Equity — Capital Quality Lens")
st.markdown(
    "A DTC-to-equity ratio above **40%** signals that a large fraction of reported capital "
    "is state-guaranteed rather than organically generated. "
    "The ratio naturally declines as equity grows (retained earnings) and DTC amortises."
)

fig_pct = go.Figure()
for bank in BANKS:
    bdata = dtc_df[dtc_df.bank == bank].sort_values("year")
    fig_pct.add_trace(go.Scatter(
        x=bdata["year"],
        y=bdata["dtc_pct_equity"],
        mode="lines+markers+text",
        name=bank,
        line=dict(color=COLORS[bank], width=2.5),
        marker=dict(size=9),
        text=[f"{v:.0f}%" for v in bdata["dtc_pct_equity"]],
        textposition="top center",
        textfont=dict(color=COLORS[bank], size=11),
        hovertemplate=f"<b>{bank}</b><br>Year: %{{x}}<br>DTC/Equity: %{{y:.1f}}%<extra></extra>",
    ))

fig_pct.add_hline(y=40, line_dash="dash", line_color="#ef4444",
                  annotation_text="40% quality threshold", annotation_font_color="#ef4444")
fig_pct.add_hline(y=25, line_dash="dot", line_color="#f59e0b",
                  annotation_text="25% target (2027)", annotation_font_color="#f59e0b")

fig_pct.update_layout(
    **LAYOUT,
    title="DTC / Total Equity (%) — Lower = Better Capital Quality",
    height=400,
    legend=dict(bgcolor="rgba(0,0,0,0)", font=dict(color="#94a3b8")),
)
fig_pct.update_xaxes(tickvals=YEARS)
fig_pct.update_yaxes(ticksuffix="%")
st.plotly_chart(fig_pct, use_container_width=True)

st.divider()

# ── Year-over-year reduction ───────────────────────────────────────────────────
st.subheader("Annual DTC Reduction (€m)")

fig_red = go.Figure()
for bank in BANKS:
    bdata = dtc_df[(dtc_df.bank == bank) & (dtc_df.yoy_change.notna())].sort_values("year")
    fig_red.add_trace(go.Bar(
        x=[f"{bank} {y}" for y in bdata["year"]],
        y=bdata["yoy_change"],
        name=bank,
        marker_color=COLORS[bank],
        text=[f"{v:+.0f}m" for v in bdata["yoy_change"]],
        textposition="outside",
        hovertemplate=f"<b>{bank}</b><br>YoY DTC Change: €%{{y:+,.0f}}m<extra></extra>",
    ))

fig_red.add_hline(y=0, line_color="#475569")
fig_red.update_layout(
    **LAYOUT,
    barmode="group",
    title="Year-over-Year DTC Change (€m) — Negative = Reduction (Good)",
    height=360,
    showlegend=False,
)
fig_red.update_yaxes(tickprefix="€", ticksuffix="m")
st.plotly_chart(fig_red, use_container_width=True)
st.caption(
    "Negative values indicate DTC is being consumed through tax-offset or voluntary derecognition. "
    "Piraeus Bank shows the fastest reduction pace (2023–2024), consistent with its accelerated "
    "derecognition commitment targeting full clean-up by 2034 vs 2041 statutory schedule."
)

st.divider()

# ── Summary table ──────────────────────────────────────────────────────────────
st.subheader("DTC Summary Table")

tbl_rows = []
for bank in BANKS:
    row = {"Bank": bank}
    for year in YEARS:
        dtc_val = DTC_DATA[bank][year]
        eq_val  = kpis[(kpis.bank == bank) & (kpis.year == year)]["equity"].values[0]
        row[f"DTC {year} (€m)"]   = f"€{dtc_val:,}m"
        row[f"DTC/Equity {year}"]  = f"{dtc_val/eq_val*100:.0f}%"
    # 2022→2024 total reduction
    total_red = DTC_DATA[bank][2022] - DTC_DATA[bank][2024]
    row["Total Reduction 22→24"]  = f"€{total_red:,}m"
    row["Pct Reduced 22→24"]       = f"{total_red/DTC_DATA[bank][2022]*100:.1f}%"
    tbl_rows.append(row)

tbl_df = pd.DataFrame(tbl_rows).set_index("Bank")
st.dataframe(tbl_df, use_container_width=True, height=215)

st.divider()

# ── Derecognition roadmap ──────────────────────────────────────────────────────
st.subheader("Derecognition Roadmap — Forward Projections")
st.markdown("""
All four banks have committed to **voluntarily deducting DTCs from CET1 capital** ahead of the
statutory tax-offset schedule, with the following public targets:

| Bank | Statutory End Date | Accelerated Target | DTC/CET1 Target by 2027 |
|------|-------------------|--------------------|-------------------------|
| Eurobank | 2041 | 2034 | ~25% |
| Alpha Bank | 2041 | 2033 | ~20–25% |
| Piraeus Bank | 2041 | **2034** (most aggressive) | ~20% |
| NBG | 2041 | 2032 | ~20–25% |

**Assumptions for forward projection below:**
- Linear annual reduction of ~€300–350m per bank (consistent with historical pace + voluntary acceleration)
- Equity grows at ~8% p.a. (retained earnings, conservative)
- No new DTC creation (PSI is a closed event; no new eligible provisions)
""")

proj_years = list(range(2022, 2035))
fig_proj = go.Figure()

# Simplified linear projection per bank from 2024 actual
DERECOG_RATE = {
    "Eurobank":     330,  # €m per year reduction
    "Alpha Bank":   350,
    "Piraeus Bank": 375,  # most aggressive
    "NBG":          320,
}

for bank in BANKS:
    dtc_2024 = DTC_DATA[bank][2024]
    rate     = DERECOG_RATE[bank]
    proj_dtc = []
    for yr in proj_years:
        if yr <= 2024:
            proj_dtc.append(DTC_DATA[bank].get(yr))
        else:
            prev = proj_dtc[-1]
            proj_dtc.append(max(0, prev - rate))

    fig_proj.add_trace(go.Scatter(
        x=proj_years,
        y=proj_dtc,
        mode="lines+markers",
        name=bank,
        line=dict(color=COLORS[bank], width=2,
                  dash="solid" if proj_years[-1] > 2024 else "solid"),
        marker=dict(size=6,
                    symbol=["circle" if y <= 2024 else "circle-open" for y in proj_years]),
        hovertemplate=f"<b>{bank}</b><br>Year: %{{x}}<br>DTC: €%{{y:,.0f}}m<extra></extra>",
    ))

fig_proj.add_vline(x=2024.5, line_dash="dot", line_color="#475569",
                   annotation_text="forecast →", annotation_font_color="#64748b")
fig_proj.update_layout(
    **LAYOUT,
    title="DTC Stock — Actual (2022–2024) + Projected Derecognition Path (2025–2034)",
    height=420,
    legend=dict(bgcolor="rgba(0,0,0,0)", font=dict(color="#94a3b8")),
)
fig_proj.update_yaxes(tickprefix="€", ticksuffix="m", rangemode="tozero")
fig_proj.update_xaxes(tickvals=list(range(2022, 2035, 2)))
st.plotly_chart(fig_proj, use_container_width=True)
st.caption(
    "Projection assumes linear derecognition at bank-specific rates (€320–375m/year). "
    "Open circles = projected; filled = actuals. "
    "Actual pace depends on each bank's voluntary deduction commitments and taxable profit generation. "
    "Source for 2022–2024 actuals: Eurobank annual report (confirmed); other banks estimated."
)

st.divider()

# ── Analyst takeaway ───────────────────────────────────────────────────────────
st.subheader("Analyst Takeaway")
st.markdown("""
**Three things every Greek banking analyst needs to know about DTCs:**

1. **It's a sovereign credit story embedded in bank capital.**
   DTC holders are ultimately relying on the Greek state to honour the guarantee if banks return to losses.
   The post-IG upgrade CRP compression (1.3% vs 2%+ pre-2023) partly reflects lower DTC tail risk.

2. **The "headline" CET1 ratios overstate capital quality relative to EU peers.**
   A German or French bank with a 15% CET1 ratio has organic, loss-absorbing capital.
   A Greek bank at 15% CET1 where 50% is DTC has materially lower quality capital.
   Adjusting for DTC brings the "organic CET1" of the four banks to ~8–10% — still above SREP floors,
   but the buffer is narrower than the headline suggests.

3. **The clean-up is structural alpha.**
   As DTC amortises and equity compounds, the DTC/equity ratio falls structurally even without
   any new earnings improvement. This is a multi-year re-rating catalyst: as DTC becomes a smaller
   fraction of CET1, the quality discount narrows, and the sector P/B multiple should converge
   toward European peers (currently trading at a 20–30% P/TBV discount to Western EU banks).
""")

st.divider()
st.caption(
    "Greek Banking Sector Analysis 2022–2024 | "
    "Analyst: Spyros Papastergiou | spyrossyo96@gmail.com  \n"
    "DTC data: Eurobank 2023/2024 confirmed (annual report); all other figures estimated. "
    "See sidebar for full data source notes."
)
